### ISSUE TITLE
Stack is becoming undefined

### ISSUE THREAD

**Issue by cdelapenaff** [jberns88/react-native-modal-queue#1]
<img width="1001" alt="Screen Shot 2020-04-15 at 5 51 56 PM" src="https://user-images.githubusercontent.com/50894769/79324384-21ceee00-7f42-11ea-9670-c7ffffa63ac4.png">

> System:
>     OS: macOS 10.15.4
>     CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
>     Memory: 1.34 GB / 16.00 GB
>     Shell: 3.2.57 - /bin/bash
>   Binaries:
>     Node: 10.15.3 - ~/.nvm/versions/node/v10.15.3/bin/node
>     Yarn: 1.17.3 - /usr/local/bin/yarn
>     npm: 6.10.3 - ~/.nvm/versions/node/v10.15.3/bin/npm
>   SDKs:
>     iOS SDK:
>       Platforms: iOS 13.4, DriverKit 19.0, macOS 10.15, tvOS 13.4, watchOS 6.2
>   IDEs:
>     Android Studio: 3.4 AI-183.6156.11.34.5522156
>     Xcode: 11.4/11E146 - /usr/bin/xcodebuild
>   npmPackages:
>     react: 16.9.0 => 16.9.0 
>     react-native: 0.61.2 => 0.61.2 
>   npmGlobalPackages:
>     react-native-cli: 2.0.1

**Suggestion:**
do this:
`const current = stack && stack[0] ? stack[0] : false;`
instead of:
`const current = stack[0] ? stack[0] : false;`
This fixes that error on my end.

Thanks for putting up this Wrapper by the way.

**Comment by jberns88** [comment]
Sorry buddy, I wasn't getting notifications for this repo for whatever reason! Merged it in.
